### ISSUE TITLE
Add Web Customer Support Functionality to Improve User Communication Efficiency

### ISSUE THREAD

**Issue by MHZ-ORG** [NikeMa2011/MCServerWebsite#1]
Background:
The website currently lacks a real-time communication feature, leaving users unable to resolve issues immediately. Adding a web-based customer support feature can significantly enhance user experience and improve consultation efficiency.

Requirements:

Add a floating customer service button in the bottom-right corner of the website.
Implement real-time chat functionality, allowing users to communicate with customer service via a text input box.
Support file exchange (e.g., images or documents).
Provide an offline message feature so users can submit issues when customer service is unavailable.
The customer service interface must support both English and Chinese language options.
Goals:

Enhance user satisfaction and loyalty.
Increase the number of consultations and users, while addressing technical requests promptly.
References:

Third-party tools: [Tidio](https://www.tidio.com/), [LiveChat](https://www.livechat.com/)
Technical Suggestions:

Start with third-party customer service plugins to quickly launch and validate the feature's effectiveness.

**Comment by NikeMa2011** [comment]
斯卡蒂一直在叫我做新的功能

________________________________
发件人: MHZ ***@***.***>
发送时间: 2024年11月18日 6:35
收件人: NikeMa2011/MCServerWebsite ***@***.***>
抄送: Subscribed ***@***.***>
主题: [NikeMa2011/MCServerWebsite] Add Web Customer Support Functionality to Improve User Communication Efficiency (Issue #1)


Background:
The website currently lacks a real-time communication feature, leaving users unable to resolve issues immediately. Adding a web-based customer support feature can significantly enhance user experience and improve consultation efficiency.

Requirements:

Add a floating customer service button in the bottom-right corner of the website.
Implement real-time chat functionality, allowing users to communicate with customer service via a text input box.
Support file exchange (e.g., images or documents).
Provide an offline message feature so users can submit issues when customer service is unavailable.
The customer service interface must support both English and Chinese language options.
Goals:

Enhance user satisfaction and loyalty.
Increase the number of consultations and users, while addressing technical requests promptly.
References:

Third-party tools: Tidio<https://www.tidio.com/>, LiveChat<https://www.livechat.com/>
Technical Suggestions:

Start with third-party customer service plugins to quickly launch and validate the feature's effectiveness.

―

**Comment by NikeMa2011** [comment]
qwq


________________________________
发件人: MHZ ***@***.***>
发送时间: 2024年11月18日 6:35
收件人: NikeMa2011/MCServerWebsite ***@***.***>
抄送: Subscribed ***@***.***>
主题: [NikeMa2011/MCServerWebsite] Add Web Customer Support Functionality to Improve User Communication Efficiency (Issue #1)


Background:
The website currently lacks a real-time communication feature, leaving users unable to resolve issues immediately. Adding a web-based customer support feature can significantly enhance user experience and improve consultation efficiency.

Requirements:

Add a floating customer service button in the bottom-right corner of the website.
Implement real-time chat functionality, allowing users to communicate with customer service via a text input box.
Support file exchange (e.g., images or documents).
Provide an offline message feature so users can submit issues when customer service is unavailable.
The customer service interface must support both English and Chinese language options.
Goals:

Enhance user satisfaction and loyalty.
Increase the number of consultations and users, while addressing technical requests promptly.
References:

Third-party tools: Tidio<https://www.tidio.com/>, LiveChat<https://www.livechat.com/>
Technical Suggestions:

Start with third-party customer service plugins to quickly launch and validate the feature's effectiveness.

―

**Comment by MHZ-ORG** [comment]
OK
