### ISSUE TITLE
代码格式需要统一

### ISSUE THREAD

**Issue by NikeMa2011** [NikeMa2011/MCServerWebsite#2]
每次上线 看到git管理图我都快要奔溃了qwq
求求你们看看代码格式说明好不好
这个"codeFormat.html"

**Comment by NikeMa2011** [comment]
![image](https://github.com/user-attachments/assets/5f9146be-74a7-4443-8c41-e64491eb8584)

**Comment by NikeMa2011** [comment]
web文件夹里

**Comment by MHZ-ORG** [comment]
OK
